import crypto from 'crypto';
import { AppError } from '../utils/AppError.js';
import { addDays, randomToken, sha256, signAccessToken, signRefreshToken, verifyRefresh } from '../utils/tokens.js';
import { RefreshToken, VerificationToken } from '../models/token.model.js';
import { userRepository } from '../repositories/user.repository.js';
import { env } from '../configs/env.js';
import { sendMail } from './mail.service.js';
export async function issueTokenPair(user, req, family = crypto.randomUUID()) { const jti = crypto.randomUUID(); const refreshToken = signRefreshToken(user, jti); await RefreshToken.create({ user: user.id, jti, tokenHash: sha256(refreshToken), family, userAgent: req.get('user-agent'), ip: req.ip, expiresAt: addDays(env.refreshDays) }); return { accessToken: signAccessToken(user), refreshToken }; }
async function createVerification(user, purpose) { const token = randomToken(); await VerificationToken.create({ user: user.id, tokenHash: sha256(token), purpose, expiresAt: new Date(Date.now() + 60 * 60 * 1000) }); return token; }
export async function register(payload, req) { if (await userRepository.findByEmail(payload.email)) throw new AppError('Email already registered', 409, 'EMAIL_EXISTS'); const user = await userRepository.create({ name: payload.name, email: payload.email, role: 'student' }); await user.setPassword(payload.password); await user.save(); const token = await createVerification(user, 'email_verification'); await sendMail({ to: user.email, subject: 'Verify your email', html: `Verification token: ${token}` }); return { user, ...(await issueTokenPair(user, req)) }; }
export async function login({ email, password }, req) { const user = await userRepository.findByEmailWithPassword(email); if (!user || !(await user.comparePassword(password))) throw new AppError('Invalid credentials', 401, 'INVALID_CREDENTIALS'); if (!user.isActive) throw new AppError('Account disabled', 403, 'ACCOUNT_DISABLED'); return { user, ...(await issueTokenPair(user, req)) }; }
export async function refresh(rawToken, req) { if (!rawToken) throw new AppError('Missing refresh token', 401, 'MISSING_REFRESH'); const payload = verifyRefresh(rawToken); const stored = await RefreshToken.findOne({ jti: payload.jti, tokenHash: sha256(rawToken) }); if (!stored || stored.revokedAt || stored.expiresAt < new Date()) throw new AppError('Refresh token revoked or expired', 401, 'REFRESH_REVOKED'); const user = await userRepository.findById(payload.sub); if (!user) throw new AppError('User not found', 401, 'USER_NOT_FOUND'); stored.revokedAt = new Date(); const nextJti = crypto.randomUUID(); stored.replacedBy = nextJti; await stored.save(); const refreshToken = signRefreshToken(user, nextJti); await RefreshToken.create({ user: user.id, jti: nextJti, tokenHash: sha256(refreshToken), family: stored.family, userAgent: req.get('user-agent'), ip: req.ip, expiresAt: addDays(env.refreshDays) }); return { user, accessToken: signAccessToken(user), refreshToken }; }
export async function verifyEmail(token) { const doc = await VerificationToken.findOne({ tokenHash: sha256(token), purpose: 'email_verification', usedAt: null }); if (!doc || doc.expiresAt < new Date()) throw new AppError('Invalid verification token', 400, 'INVALID_TOKEN'); await userRepository.updateById(doc.user, { isEmailVerified: true }); doc.usedAt = new Date(); await doc.save(); }
export async function forgotPassword(email) { const user = await userRepository.findByEmail(email); if (!user) return; const token = await createVerification(user, 'password_reset'); await sendMail({ to: user.email, subject: 'Reset your password', html: `Reset token: ${token}` }); }
export async function resetPassword(token, password) { const doc = await VerificationToken.findOne({ tokenHash: sha256(token), purpose: 'password_reset', usedAt: null }); if (!doc || doc.expiresAt < new Date()) throw new AppError('Invalid reset token', 400, 'INVALID_TOKEN'); const user = await userRepository.findById(doc.user); await user.setPassword(password); await user.save(); doc.usedAt = new Date(); await doc.save(); await RefreshToken.updateMany({ user: user.id, revokedAt: null }, { revokedAt: new Date() }); }
export async function logout(rawToken) { if (rawToken) await RefreshToken.findOneAndUpdate({ tokenHash: sha256(rawToken) }, { revokedAt: new Date() }); }
export async function logoutAll(userId) { await RefreshToken.updateMany({ user: userId, revokedAt: null }, { revokedAt: new Date() }); }
